# Generated by Django 3.1.5 on 2021-02-02 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cfuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coffeecode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfcode', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '커피 코드',
                'verbose_name_plural': '커피 코드',
                'db_table': 'cfcode name',
            },
        ),
        migrations.CreateModel(
            name='Cfproduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='제목')),
                ('price', models.TextField(verbose_name='내용')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('cfcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfproduct.coffeecode', verbose_name='커피종류')),
            ],
            options={
                'verbose_name': '커피',
                'verbose_name_plural': '커피',
                'db_table': 'coffeeshop coffee',
            },
        ),
        migrations.CreateModel(
            name='BuyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50, verbose_name='주소')),
                ('buy_method', models.SmallIntegerField(choices=[(0, 'credit'), (1, 'cash'), (2, 'kakaopay')])),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfuser.cfuser', verbose_name='구매자')),
            ],
            options={
                'verbose_name': '구매정보',
                'verbose_name_plural': '구매정보',
                'db_table': 'buyer info',
            },
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='주문수량')),
                ('buy_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfproduct.buyinfo', verbose_name='구매정보')),
                ('cfname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfproduct.cfproduct', verbose_name='커피')),
            ],
            options={
                'verbose_name': '구매',
                'verbose_name_plural': '구매',
                'db_table': 'buy detail',
            },
        ),
    ]
