# Generated by Django 3.1.5 on 2021-02-03 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cfoption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='옵션명')),
            ],
            options={
                'verbose_name': '옵션명',
                'verbose_name_plural': '옵션명',
                'db_table': 'coffeeoption table',
            },
        ),
        migrations.CreateModel(
            name='Cfproduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('price', models.IntegerField(verbose_name='price')),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images')),
            ],
            options={
                'verbose_name': '커피',
                'verbose_name_plural': '커피',
                'db_table': 'coffeeshop coffee',
            },
        ),
        migrations.CreateModel(
            name='Coffeecode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfcode', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '커피 코드',
                'verbose_name_plural': '커피 코드',
                'db_table': 'cfcode name',
            },
        ),
        migrations.CreateModel(
            name='Optiondetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=30, verbose_name='옵션')),
                ('option_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfproduct.cfoption', verbose_name='옵션명')),
            ],
            options={
                'verbose_name': '옵션',
                'verbose_name_plural': '옵션',
                'db_table': 'coffee option',
            },
        ),
        migrations.CreateModel(
            name='CftoOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfproduct.cfproduct', verbose_name='커피명')),
                ('option_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfproduct.cfoption', verbose_name='옵션명')),
            ],
            options={
                'verbose_name': '커피_옵션',
                'verbose_name_plural': '커피_옵션',
                'db_table': 'coffee to option',
            },
        ),
        migrations.AddField(
            model_name='cfproduct',
            name='cfcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfproduct.coffeecode', verbose_name='커피종류'),
        ),
    ]
