# Generated by Django 3.1.5 on 2021-02-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfproduct', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfproduct',
            name='price',
            field=models.IntegerField(verbose_name='price'),
        ),
    ]
