# Generated by Django 3.1.5 on 2021-02-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfproduct', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opcode',
            options={'verbose_name': '옵션코드', 'verbose_name_plural': '옵션코드'},
        ),
        migrations.RemoveField(
            model_name='cfoption',
            name='amount',
        ),
        migrations.AddField(
            model_name='cftooption',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='추가금액'),
        ),
    ]
