# Generated by Django 3.1.5 on 2021-02-03 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfproduct', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='optiondetail',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='추가금액'),
        ),
    ]
