# Generated by Django 3.1.5 on 2021-02-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfproduct', '0002_auto_20210203_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfoption',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='수량'),
        ),
    ]
