# Generated by Django 3.1.5 on 2021-02-04 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfproduct', '0003_cfoption_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cfoption',
            name='quantity',
        ),
    ]
