# Generated by Django 3.1.5 on 2021-02-08 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cfproduct', '0004_remove_cfoption_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cftooption',
            name='cf_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cfproduct.coffeecode', verbose_name='커피코드'),
        ),
    ]
