# Generated by Django 3.1.5 on 2021-02-09 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cfuser', '0002_cfuser_image'),
        ('cfproduct', '0006_remove_cftooption_cf_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cfcomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField(verbose_name='내용')),
                ('coffee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfproduct.cfproduct', verbose_name='커피')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfuser.cfuser', verbose_name='작성자')),
            ],
            options={
                'verbose_name': '댓글',
                'verbose_name_plural': '댓글',
                'db_table': 'coffee comment',
            },
        ),
    ]
