# Generated by Django 3.1.5 on 2021-02-09 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfuser',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images'),
        ),
    ]
