# Generated by Django 3.1.5 on 2021-01-26 07:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cfboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boardcate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catename', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Boardcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardname', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='boardname',
            field=models.ForeignKey(default="", on_delete=django.db.models.deletion.CASCADE, to='cfboard.boardcode', verbose_name='보드종류'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='catename',
            field=models.ForeignKey(default="", on_delete=django.db.models.deletion.CASCADE, to='cfboard.boardcate', verbose_name='카테고리'),
            preserve_default=False,
        ),
    ]
