# Generated by Django 3.1.5 on 2021-01-26 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfuser', '0001_initial'),
        ('cfboard', '0002_auto_20210126_1654'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Board',
            new_name='Cfboard',
        ),
    ]
