# Generated by Django 3.1.5 on 2021-01-26 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfboard', '0003_auto_20210126_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardcate',
            options={'verbose_name': '카테고리', 'verbose_name_plural': '카테고리'},
        ),
        migrations.AlterModelOptions(
            name='boardcode',
            options={'verbose_name': '게시판종류', 'verbose_name_plural': '게시판종류'},
        ),
        migrations.AlterModelOptions(
            name='cfboard',
            options={'verbose_name': '게시판', 'verbose_name_plural': '게시판'},
        ),
        migrations.AlterModelTable(
            name='boardcate',
            table='board category',
        ),
        migrations.AlterModelTable(
            name='boardcode',
            table='board name',
        ),
    ]
