# Generated by Django 3.1.5 on 2021-02-01 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfboard', '0005_boardcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardcomment',
            old_name='writer',
            new_name='user',
        ),
    ]
