# Generated by Django 3.1.5 on 2021-02-02 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cfboard', '0006_auto_20210201_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardcomment',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfboard.cfboard', verbose_name='게시글'),
        ),
    ]
