# Generated by Django 3.1.5 on 2021-02-03 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cfproduct', '0001_initial'),
        ('cfuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basketdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='수량')),
                ('amount', models.IntegerField(default=0, verbose_name='금액')),
            ],
            options={
                'verbose_name': '장바구니상세',
                'verbose_name_plural': '장바구니상세',
                'db_table': 'basket detail',
            },
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50, verbose_name='주소')),
                ('buy_method', models.SmallIntegerField(choices=[(0, 'credit'), (1, 'cash'), (2, 'kakaopay')])),
                ('buy_date', models.DateTimeField(auto_now_add=True, verbose_name='구매일자')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfuser.cfuser', verbose_name='구매자')),
            ],
            options={
                'verbose_name': '구매',
                'verbose_name_plural': '구매',
                'db_table': 'buyer info',
            },
        ),
        migrations.CreateModel(
            name='Buydetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='주문수량')),
                ('amount', models.IntegerField(default=0, verbose_name='주문 총 금액')),
                ('buy_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfbuy.buy', verbose_name='구매정보')),
            ],
            options={
                'verbose_name': '구매상세',
                'verbose_name_plural': '구매상세',
                'db_table': 'buyer detail',
            },
        ),
        migrations.CreateModel(
            name='Shoppingbasket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfuser.cfuser', verbose_name='구매자')),
            ],
            options={
                'verbose_name': '장바구니',
                'verbose_name_plural': '장바구니',
                'db_table': 'basket table',
            },
        ),
        migrations.CreateModel(
            name='Cfselect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfbuy.basketdetail', verbose_name='장바구니내역')),
                ('buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfbuy.buydetail', verbose_name='구매내역')),
                ('cfoption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfproduct.cftooption', verbose_name='구매제품')),
            ],
            options={
                'verbose_name': '구매제품',
                'verbose_name_plural': '구매제품',
                'db_table': 'coffee select',
            },
        ),
        migrations.AddField(
            model_name='basketdetail',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfbuy.shoppingbasket', verbose_name='장바구니'),
        ),
    ]
