# Generated by Django 3.1.5 on 2021-02-08 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cfproduct', '0006_remove_cftooption_cf_code'),
        ('cfuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basketdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='금액')),
                ('quantity', models.IntegerField(default=1, verbose_name='수량')),
            ],
            options={
                'verbose_name': '장바구니상세',
                'verbose_name_plural': '장바구니상세',
                'db_table': 'basket detail',
            },
        ),
        migrations.CreateModel(
            name='Buydetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='주문 총 금액')),
                ('quantity', models.IntegerField(default=1, verbose_name='수량')),
            ],
            options={
                'verbose_name': '구매상세',
                'verbose_name_plural': '구매상세',
                'db_table': 'buyer detail',
            },
        ),
        migrations.CreateModel(
            name='Cfselect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cfbuy.basketdetail', verbose_name='장바구니내역')),
                ('buy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cfbuy.buydetail', verbose_name='구매내역')),
                ('cf_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cfproduct.coffeecode', verbose_name='커피코드')),
                ('cfoption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfproduct.cftooption', verbose_name='구매제품')),
            ],
            options={
                'verbose_name': '구매제품',
                'verbose_name_plural': '구매제품',
                'db_table': 'coffee select',
            },
        ),
        migrations.CreateModel(
            name='Cfbuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(default='', max_length=20, verbose_name='수령인')),
                ('postcode', models.CharField(default='', max_length=20, verbose_name='우편번호')),
                ('roadAddress', models.CharField(default='', max_length=50, verbose_name='도로명주소')),
                ('jubunAddress', models.CharField(blank='true', max_length=50, null='true', verbose_name='지번주소')),
                ('detailAddress', models.CharField(default='', max_length=50, verbose_name='상세주소')),
                ('buy_method', models.SmallIntegerField(choices=[(0, 'credit'), (1, 'cash'), (2, 'kakaopay')])),
                ('phone', models.CharField(default='', max_length=20, verbose_name='전화번호')),
                ('email', models.CharField(default='', max_length=50, verbose_name='email')),
                ('buy_date', models.DateTimeField(auto_now_add=True, verbose_name='구매일자')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfuser.cfuser', verbose_name='구매자')),
            ],
            options={
                'verbose_name': '구매',
                'verbose_name_plural': '구매',
                'db_table': 'buyer info',
            },
        ),
        migrations.AddField(
            model_name='buydetail',
            name='buy_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfbuy.cfbuy', verbose_name='구매정보'),
        ),
    ]
