# Generated by Django 3.1.5 on 2021-02-08 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cfproduct', '0005_cftooption_cf_code'),
        ('cfbuy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfselect',
            name='cf_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cfproduct.coffeecode', verbose_name='커피코드'),
        ),
    ]
