# Generated by Django 3.1.5 on 2021-02-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfbuy', '0002_remove_basketdetail_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketdetail',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='수량'),
        ),
    ]
