# Generated by Django 3.1.5 on 2021-02-08 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfbuy', '0002_cfselect_cf_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cfselect',
            name='quantity',
        ),
        migrations.AddField(
            model_name='buydetail',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='수량'),
        ),
    ]
