# Generated by Django 3.1.5 on 2021-02-03 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfbuy', '0002_remove_basketdetail_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buydetail',
            name='quantity',
        ),
    ]
