# Generated by Django 3.1.5 on 2021-02-03 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cfbuy', '0003_remove_buydetail_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfselect',
            name='basket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cfbuy.basketdetail', verbose_name='장바구니내역'),
        ),
        migrations.AlterField(
            model_name='cfselect',
            name='buy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cfbuy.buydetail', verbose_name='구매내역'),
        ),
    ]
