# Generated by Django 3.1.5 on 2021-02-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfbuy', '0004_auto_20210203_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfselect',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='수량'),
        ),
    ]
