# Generated by Django 3.1.5 on 2021-02-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfbuy', '0005_auto_20210208_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cfbuy',
            name='jubunAddress',
        ),
        migrations.RemoveField(
            model_name='cfbuy',
            name='roadAddress',
        ),
        migrations.AddField(
            model_name='cfbuy',
            name='address',
            field=models.CharField(default='', max_length=50, verbose_name='주소'),
        ),
        migrations.AddField(
            model_name='cfbuy',
            name='extraAddress',
            field=models.CharField(blank='true', max_length=50, null='true', verbose_name='참고항목'),
            preserve_default='true',
        ),
    ]
