# Generated by Django 3.1.5 on 2021-02-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfbuy', '0007_auto_20210208_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfbuy',
            name='delivery_msg',
            field=models.CharField(default='', max_length=100, verbose_name='delivery_msg'),
        ),
    ]
