# Generated by Django 3.1.5 on 2021-02-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfbuy', '0008_cfbuy_delivery_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfbuy',
            name='delivery_msg',
            field=models.CharField(blank='true', default='', max_length=100, null='true', verbose_name='delivery_msg'),
        ),
    ]
