# Generated by Django 3.1.5 on 2021-02-08 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfbuy', '0013_cfbuy_buy_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buydetail',
            name='buy_date',
        ),
    ]
